Repository duckdb/pg_duckdb, pull requests merged in 2024-10, with the labels that each got.

#237 Use -Werror in CI
  .github/workflows/build_and_test.yaml
  Makefile
Labels: testing

#242 Automatically download git submodule
  Makefile
Labels: developer experience

#221 Switch CI to Ubuntu 24.04
  .github/workflows/build_and_test.yaml
Labels: testing

#248 fix builds that use older clang versions
  Makefile
Labels: developer experience

#246 Call `GetActiveSnapshot` when creating TX
  include/pgduckdb/catalog/pgduckdb_storage.hpp
  include/pgduckdb/catalog/pgduckdb_transaction_manager.hpp
  src/catalog/pgduckdb_storage.cpp
  src/catalog/pgduckdb_transaction_manager.cpp
  src/pgduckdb_duckdb.cpp
  test/regression/expected/transaction_errors.out
  test/regression/schedule
  test/regression/sql/transaction_errors.sql
Labels: bug

#252 Get rid of PostgresContextState
  include/pgduckdb/scan/postgres_scan.hpp
  src/catalog/pgduckdb_transaction.cpp
  src/pgduckdb_duckdb.cpp
  src/scan/postgres_scan.cpp
Labels: refactoring

#251 Fix memory leaks in custom executor
  include/pgduckdb/pgduckdb_utils.hpp
  src/pgduckdb_node.cpp
Labels: bug

#231 Add DuckDB temporary tables
  include/pgduckdb/pgduckdb_ddl.hpp
  include/pgduckdb/pgduckdb_metadata_cache.hpp
  include/pgduckdb/pgduckdb_ruleutils.h
  include/pgduckdb/pgduckdb_table_am.hpp
  include/pgduckdb/utility/rename_ruleutils.h
  sql/pg_duckdb--0.0.1.sql
  src/pgduckdb_ddl.cpp
  src/pgduckdb_duckdb.cpp
  src/pgduckdb_hooks.cpp
  src/pgduckdb_metadata_cache.cpp
  src/pgduckdb_planner.cpp
  src/pgduckdb_ruleutils.cpp
  src/pgduckdb_table_am.cpp
  src/vendor/pg_ruleutils_15.c
  src/vendor/pg_ruleutils_16.c
  src/vendor/pg_ruleutils_17.c
  test/pycheck/conftest.py
  test/pycheck/prepared_test.py
  test/pycheck/utils.py
  test/regression/expected/basic.out
  test/regression/expected/execution_error.out
  test/regression/expected/temporary_tables.out
  test/regression/expected/transaction_errors.out
  test/regression/schedule
  test/regression/sql/basic.sql
  test/regression/sql/temporary_tables.sql
Labels: enhancement

#257 cleanup duckdb build
  .github/workflows/build_and_test.yaml
  Makefile
Labels: developer experience

#262 ci: improve gha ccache caching key
  .github/workflows/build_and_test.yaml
Labels: developer experience

#259 Create a single way of creating a connection
  include/pgduckdb/pgduckdb_duckdb.hpp
  src/pgduckdb_ddl.cpp
  src/pgduckdb_duckdb.cpp
  src/pgduckdb_options.cpp
  src/pgduckdb_planner.cpp
  src/utility/copy.cpp
Labels: refactoring

#253 Sync after each insert/update/delete of `duckdb.secrets` table
  include/pgduckdb/pgduckdb_duckdb.hpp
  sql/pg_duckdb--0.0.1.sql
  src/pgduckdb_duckdb.cpp
  test/regression/expected/secrets.out
  test/regression/schedule
  test/regression/sql/secrets.sql
Labels: bug

#269 Small cleanups
  include/pgduckdb/pgduckdb_utils.hpp
  src/pgduckdb_node.cpp
Labels: refactoring

#256 Fix memory leaks in custom executor
  include/pgduckdb/pgduckdb_utils.hpp
  src/pgduckdb_node.cpp
  src/pgduckdb_planner.cpp
Labels: bug

#88 Local object cache for cached_httpfs extension
  README.md
  include/pgduckdb/pgduckdb_options.hpp
  include/pgduckdb/pgduckdb_utils.hpp
  sql/pg_duckdb--0.0.1.sql
  src/pgduckdb_duckdb.cpp
  src/pgduckdb_options.cpp
  src/pgduckdb_utils.cpp
  third_party/cached_httpfs/CMakeLists.txt
  third_party/cached_httpfs/README.md
  third_party/cached_httpfs/cached_httpfs_extension.cpp
  third_party/cached_httpfs/create_secret_functions.cpp
  third_party/cached_httpfs/hffs.cpp
  third_party/cached_httpfs/http_file_cache.cpp
  third_party/cached_httpfs/http_state.cpp
  third_party/cached_httpfs/httpfs.cpp
  third_party/cached_httpfs/httpfs_config.py
  third_party/cached_httpfs/include/create_secret_functions.hpp
  third_party/cached_httpfs/include/http_file_cache.hpp
  third_party/cached_httpfs/include/http_metadata_cache.hpp
  third_party/cached_httpfs/include/http_state.hpp
  third_party/cached_httpfs/include/httpfs.hpp
  third_party/cached_httpfs/include/s3fs.hpp
  third_party/cached_httpfs/s3fs.cpp
Labels: enhancement

#274 Only load pg_duckdb extension if set in shared_preload_variables
  src/pgduckdb.cpp
Labels: documentation, enhancement

#264 Rewrite COPY ... TO command to match pgduckdb execution
  src/pgduckdb_hooks.cpp
  src/utility/copy.cpp
Labels: bug

#276 Fix foreach_ptr to work in C++ code
  include/pgduckdb/vendor/pg_list.hpp
Labels: developer experience

#241 Add support for CREATE TABLE AS for duckdb TableAM
  src/pgduckdb_ddl.cpp
  test/pycheck/explain_test.py
  test/pycheck/prepared_test.py
  test/regression/expected/temporary_tables.out
  test/regression/sql/temporary_tables.sql
Labels: enhancement

#277 Improve error when read_xxx functions fail
  include/pgduckdb/pgduckdb_planner.hpp
  src/pgduckdb_hooks.cpp
  src/pgduckdb_planner.cpp
  test/regression/expected/read_functions.out
  test/regression/sql/read_functions.sql
Labels: bug, enhancement

#275 Add missing iceberg_* functions with parameters
  sql/pg_duckdb--0.0.1.sql
  src/pgduckdb_metadata_cache.cpp
  src/pgduckdb_types.cpp
Labels: enhancement

#267 Add MotherDuck support
  Makefile
  include/pgduckdb/pgduckdb.h
  include/pgduckdb/pgduckdb_background_worker.hpp
  include/pgduckdb/pgduckdb_duckdb.hpp
  include/pgduckdb/pgduckdb_metadata_cache.hpp
  include/pgduckdb/pgduckdb_ruleutils.h
  include/pgduckdb/pgduckdb_types.hpp
  sql/pg_duckdb--0.0.1.sql
  src/pgduckdb.cpp
  src/pgduckdb_background_worker.cpp
  src/pgduckdb_ddl.cpp
  src/pgduckdb_duckdb.cpp
  src/pgduckdb_metadata_cache.cpp
  src/pgduckdb_ruleutils.cpp
  src/pgduckdb_types.cpp
  test/regression/expected/temporary_tables.out
Labels: enhancement

#290 Small improvements to secret and extension management
  README.md
  include/pgduckdb/pgduckdb_options.hpp
  sql/pg_duckdb--0.0.1.sql
  src/pgduckdb_duckdb.cpp
  src/pgduckdb_options.cpp
  test/regression/expected/secrets.out
  test/regression/sql/secrets.sql
Labels: bug, enhancement

#291 Allow configuring of DuckDB settings
  include/pgduckdb/pgduckdb.h
  src/pgduckdb.cpp
  src/pgduckdb_duckdb.cpp
Labels: enhancement

#293 Handle custom DateStyle correctly
  include/pgduckdb/pgduckdb_ruleutils.h
  include/pgduckdb/utility/rename_ruleutils.h
  include/pgduckdb/vendor/pg_ruleutils.h
  src/pgduckdb_ddl.cpp
  src/pgduckdb_planner.cpp
  src/pgduckdb_ruleutils.cpp
  src/utility/copy.cpp
  test/regression/expected/temporary_tables.out
  test/regression/sql/temporary_tables.sql
Labels: bug

#292 Support for TIMESTAMPTZ
  src/pgduckdb_filter.cpp
  src/pgduckdb_types.cpp
  test/pycheck/prepared_test.py
  test/regression/expected/type_support.out
  test/regression/sql/type_support.sql
Labels: enhancement

#294 Add `disabled_filesystems` support
  include/pgduckdb/pgduckdb.h
  src/pgduckdb.cpp
  src/pgduckdb_duckdb.cpp
Labels: enhancement, security

#53 Docker image
  .dockerignore
  .github/workflows/docker.yaml
  Dockerfile
  docker-bake.hcl
Labels: developer experience

#305 Pre-configure docker image to use pg_duckdb
  Dockerfile
Labels: documentation, developer experience

#301 Add issue template
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/maintainers_issue.yml
Labels: documentation, developer experience

#307 de-matrix the docker platforms
  .github/workflows/docker.yaml
Labels: bug

#303 Docker compose
  docker-compose.yml
  docker/postgresql.conf
Labels: documentation, developer experience

#322 Lookup is_null correctly in case of pushed down filters
  src/pgduckdb_types.cpp
  test/regression/expected/correct_null_conversions.out
  test/regression/schedule
  test/regression/sql/correct_null_conversions.sql
Labels: bug

#316 Synchronise extensions before reconnect
  include/pgduckdb/pgduckdb_duckdb.hpp
  sql/pg_duckdb--0.0.1.sql
  src/pgduckdb_duckdb.cpp
  src/pgduckdb_options.cpp
  test/regression/expected/extensions.out
  test/regression/expected/secrets.out
  test/regression/schedule
  test/regression/sql/extensions.sql
  test/regression/sql/secrets.sql
Labels: bug
