Repository duckdb/pg_duckdb, pull requests merged in 2024-09, with the labels that each got.

#208 Add the ability to run a single test
  test/regression/Makefile
Labels: developer experience

#211 Makefile improvements
  .github/workflows/build_and_test.yaml
  Makefile
Labels: developer experience

#232 Enable LZ4 in CI postgres build
  .github/workflows/build_and_test.yaml
Labels: testing

#233 Always run CI
  .github/workflows/build_and_test.yaml
Labels: testing

#230 Document casing of C implementations of SQL functions
  CONTRIBUTING.md
Labels: documentation

#180 support postgresql 15
  .github/workflows/build_and_test.yaml
  src/pgduckdb_detoast.cpp
  src/pgduckdb_hooks.cpp
  src/pgduckdb_planner.cpp
  src/utility/copy.cpp
  src/vendor/pg_ruleutils_15.c
  test/regression/expected/basic.out
  test/regression/expected/type_support.out
  test/regression/sql/basic.sql
  test/regression/sql/type_support.sql
Labels: enhancement
